/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import dao.PatrimonioDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neto-PC
 */
public class BaixaPatrimonial extends javax.swing.JFrame {

    /**
     * Creates new form BaixaPatrimonial
     */
    public BaixaPatrimonial() {
        initComponents();
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        carregarTabela();
    }
    
    private void carregarTabela(){
        String[] tableColumnsName = {"Código", "Nº Proc.de Entrada", "Nº Nota Fiscal", 
            "Nome", "Marca", "Modelo", "Nº Série", "Descrição", "Mod. Aquisição", "Valor", "Local"}; 
        
        DefaultTableModel aModel = (DefaultTableModel) tabRelatBaixaPatri.getModel();
        aModel.setColumnIdentifiers(tableColumnsName); 

        tabRelatBaixaPatri.setModel(PatrimonioDAO.readAll(1, aModel));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSairRelatBaixa = new javax.swing.JButton();
        btnImprimirRelatBaixa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabRelatBaixaPatri = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório Baixa Patrimonial ");

        btnSairRelatBaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSairRelatBaixa.setForeground(new java.awt.Color(255, 0, 0));
        btnSairRelatBaixa.setText("Sair");
        btnSairRelatBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairRelatBaixaActionPerformed(evt);
            }
        });

        btnImprimirRelatBaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimirRelatBaixa.setForeground(new java.awt.Color(0, 102, 255));
        btnImprimirRelatBaixa.setText("Imprimir");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("RELATÓRIO DE BAIXA PATRIMONIAL");

        tabRelatBaixaPatri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabRelatBaixaPatri.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        tabRelatBaixaPatri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nº Proc.de Entrada", "Nº Nota Fiscal", "Nome", "Marca", "Modelo", "Nº Série", "Descrição", "Mod. Aquisição", "Valor", "Local"
            }
        ));
        tabRelatBaixaPatri.setEnabled(false);
        jScrollPane1.setViewportView(tabRelatBaixaPatri);
        if (tabRelatBaixaPatri.getColumnModel().getColumnCount() > 0) {
            tabRelatBaixaPatri.getColumnModel().getColumn(0).setPreferredWidth(35);
            tabRelatBaixaPatri.getColumnModel().getColumn(1).setPreferredWidth(90);
            tabRelatBaixaPatri.getColumnModel().getColumn(2).setPreferredWidth(60);
            tabRelatBaixaPatri.getColumnModel().getColumn(3).setPreferredWidth(110);
            tabRelatBaixaPatri.getColumnModel().getColumn(4).setPreferredWidth(60);
            tabRelatBaixaPatri.getColumnModel().getColumn(5).setPreferredWidth(60);
            tabRelatBaixaPatri.getColumnModel().getColumn(6).setPreferredWidth(35);
            tabRelatBaixaPatri.getColumnModel().getColumn(7).setPreferredWidth(120);
            tabRelatBaixaPatri.getColumnModel().getColumn(8).setPreferredWidth(65);
            tabRelatBaixaPatri.getColumnModel().getColumn(9).setPreferredWidth(35);
            tabRelatBaixaPatri.getColumnModel().getColumn(10).setPreferredWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(283, 283, 283))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimirRelatBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSairRelatBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairRelatBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirRelatBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairRelatBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairRelatBaixaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairRelatBaixaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirRelatBaixa;
    private javax.swing.JButton btnSairRelatBaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabRelatBaixaPatri;
    // End of variables declaration//GEN-END:variables
}
