/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import bean.Patrimonio;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto-PC
 */
public class CadastrarPatri extends javax.swing.JFrame {

    String action = "";
    Patrimonio patrimonio = new Patrimonio();
    
    /**
     * Creates new form Cadastrar
     */
    public CadastrarPatri() {
        initComponents();
        setLocationRelativeTo(null);
        
        action = "cadastrar";
        
        txtCodCadPatri.setEnabled(false);
        btnBaixaCadPatri.setVisible(false);
        btnAlterarCadPatri.setVisible(false);
        
    }
    
    public CadastrarPatri(Patrimonio patrimonio) {
        initComponents();
        setLocationRelativeTo(null);

        this.patrimonio = patrimonio;
        inicializarCampos();

        txtCodCadPatri.setEnabled(false);
        btnOkCadPatri.setEnabled(false);
        
        action = "alterar";
    }

    private void inicializarCampos() {
        txtCodCadPatri.setText(Integer.toString(patrimonio.getCodPatrimonio()));
        txtDescricaoCadPatri.setText(patrimonio.getDescricaoPatrimonio());
        txtLocalCadPatri.setText(patrimonio.getLocalPatrimonio());
        txtMarcaCadPatri.setText(patrimonio.getMarcaPatrimonio());
        txtModalAquiCadPatri.setText(patrimonio.getModAquPatrimonio());
        txtModeloCadPatri.setText(patrimonio.getModeloPatrimonio());
        txtNProcCadPatri.setText(Integer.toString(patrimonio.getNumProcEntrada()));
        txtNSerieCadPatri.setText(Integer.toString(patrimonio.getNumSeriePatrimonio()));
        txtNfCadPatri.setText(Integer.toString(patrimonio.getNumNotaFiscal()));
        txtNomeCadPatri.setText(patrimonio.getNomePatrimonio());
        txtValorCadPatri.setText(Float.toString(patrimonio.getValorPatrimonio()));
    }
    
    private void setPatrimonio(){
        patrimonio.setDescricaoPatrimonio(txtDescricaoCadPatri.getText());
        patrimonio.setLocalPatrimonio(txtLocalCadPatri.getText());
        patrimonio.setMarcaPatrimonio(txtMarcaCadPatri.getText());
        patrimonio.setModAquPatrimonio(txtModalAquiCadPatri.getText());
        patrimonio.setModeloPatrimonio(txtModeloCadPatri.getText());
        patrimonio.setNumProcEntrada(Integer.parseInt(txtNProcCadPatri.getText()));
        patrimonio.setNumSeriePatrimonio(Integer.parseInt(txtNSerieCadPatri.getText()));
        patrimonio.setNumNotaFiscal(Integer.parseInt(txtNfCadPatri.getText()));
        patrimonio.setNomePatrimonio(txtNomeCadPatri.getText());
        patrimonio.setValorPatrimonio(Float.parseFloat(txtValorCadPatri.getText()));
    }
    
    private boolean validateForm(){
        if (txtDescricaoCadPatri.getText().equals("") ||
            txtMarcaCadPatri.getText().equals("") ||
            txtModalAquiCadPatri.getText().equals("") ||
            txtModeloCadPatri.getText().equals("") ||
            txtNProcCadPatri.getText().equals("") ||
            txtNSerieCadPatri.getText().equals("") ||
            txtNfCadPatri.getText().equals("") ||
            txtNomeCadPatri.getText().equals("") ||
            txtValorCadPatri.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            return false;
        }
        
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodCadPatri = new javax.swing.JTextField();
        txtNProcCadPatri = new javax.swing.JTextField();
        txtNfCadPatri = new javax.swing.JTextField();
        txtNomeCadPatri = new javax.swing.JTextField();
        txtMarcaCadPatri = new javax.swing.JTextField();
        txtDescricaoCadPatri = new javax.swing.JTextField();
        txtModeloCadPatri = new javax.swing.JTextField();
        txtNSerieCadPatri = new javax.swing.JTextField();
        txtLocalCadPatri = new javax.swing.JTextField();
        txtModalAquiCadPatri = new javax.swing.JTextField();
        txtValorCadPatri = new javax.swing.JTextField();
        btnOkCadPatri = new javax.swing.JButton();
        btnLimparCadPatri = new javax.swing.JButton();
        btnCancelarCadPatri = new javax.swing.JButton();
        btnAlterarCadPatri = new javax.swing.JButton();
        btnBaixaCadPatri = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Patrimônio");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nº Processo de Entrada:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nº Nota Fiscal:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Marca:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Modelo:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Nº Série:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Descrição:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Valor:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Modalidade Aquisição:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Local:");

        txtCodCadPatri.setBackground(new java.awt.Color(204, 204, 204));
        txtCodCadPatri.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNProcCadPatri.setToolTipText("");

        txtModeloCadPatri.setToolTipText("");

        btnOkCadPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOkCadPatri.setForeground(new java.awt.Color(0, 102, 255));
        btnOkCadPatri.setText("OK");
        btnOkCadPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkCadPatriActionPerformed(evt);
            }
        });

        btnLimparCadPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimparCadPatri.setText("Limpar");
        btnLimparCadPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCadPatriActionPerformed(evt);
            }
        });

        btnCancelarCadPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarCadPatri.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelarCadPatri.setText("Cancelar");
        btnCancelarCadPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadPatriActionPerformed(evt);
            }
        });

        btnAlterarCadPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterarCadPatri.setForeground(new java.awt.Color(0, 102, 255));
        btnAlterarCadPatri.setText("Alterar");
        btnAlterarCadPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCadPatriActionPerformed(evt);
            }
        });

        btnBaixaCadPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBaixaCadPatri.setForeground(new java.awt.Color(0, 102, 255));
        btnBaixaCadPatri.setText("Dar Baixa");
        btnBaixaCadPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixaCadPatriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCodCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNProcCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNfCadPatri, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                    .addComponent(txtDescricaoCadPatri)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtModeloCadPatri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                        .addComponent(txtNomeCadPatri, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(txtMarcaCadPatri, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                        .addComponent(txtNSerieCadPatri)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBaixaCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnAlterarCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtModalAquiCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLocalCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOkCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnLimparCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnCancelarCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNProcCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNfCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcaCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModeloCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNSerieCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricaoCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModalAquiCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLocalCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValorCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaixaCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarCadPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaixaCadPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixaCadPatriActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente dar baixa?", "Confirmar Baixa de Patrimônio", JOptionPane.YES_NO_OPTION);
        if (escolha == JOptionPane.YES_OPTION) {
            setPatrimonio();
            patrimonio.setBaixaPatrimonio(true);
            patrimonio.Alterar();
            JOptionPane.showMessageDialog(null, "Baixa Patrimonial realizada com sucesso!");
        }
        else if (escolha == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Baixa Patrimonial não realizada!");
        }
    }//GEN-LAST:event_btnBaixaCadPatriActionPerformed

    private void btnAlterarCadPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCadPatriActionPerformed
        btnAlterarCadPatri.setEnabled(false);
        btnBaixaCadPatri.setEnabled(false);
        btnOkCadPatri.setEnabled(true);
    }//GEN-LAST:event_btnAlterarCadPatriActionPerformed

    private void btnOkCadPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkCadPatriActionPerformed
        
        if(!validateForm()){
            return;
        }
        
        patrimonio.setBaixaPatrimonio(false);
        setPatrimonio();
        
        switch (action) {
            case "alterar":
                patrimonio.Alterar();
                btnAlterarCadPatri.setEnabled(true);
                btnBaixaCadPatri.setEnabled(true);
                btnOkCadPatri.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Patrimônio alterado com sucesso!");
                break;
            case "cadastrar":
                patrimonio.Cadastrar();
                this.dispose();
                JOptionPane.showMessageDialog(null, "Patrimônio cadastrado com sucesso!");
                break;
            default:
                this.dispose();
                break;
        }
    }//GEN-LAST:event_btnOkCadPatriActionPerformed

    private void btnLimparCadPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCadPatriActionPerformed
        if (action.equals("alterar")) {
            inicializarCampos();
        } else {
            txtCodCadPatri.setText("");
            txtDescricaoCadPatri.setText("");
            txtLocalCadPatri.setText("");
            txtMarcaCadPatri.setText("");
            txtModalAquiCadPatri.setText("");
            txtModeloCadPatri.setText("");
            txtNProcCadPatri.setText("");
            txtNSerieCadPatri.setText("");
            txtNfCadPatri.setText("");
            txtNomeCadPatri.setText("");
            txtValorCadPatri.setText("");
        }
    }//GEN-LAST:event_btnLimparCadPatriActionPerformed

    private void btnCancelarCadPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadPatriActionPerformed
        if (action.equals("alterar")) {
            btnAlterarCadPatri.setEnabled(true);
            btnBaixaCadPatri.setEnabled(true);
            btnOkCadPatri.setEnabled(false);
            inicializarCampos();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarCadPatriActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCadPatri;
    private javax.swing.JButton btnBaixaCadPatri;
    private javax.swing.JButton btnCancelarCadPatri;
    private javax.swing.JButton btnLimparCadPatri;
    private javax.swing.JButton btnOkCadPatri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtCodCadPatri;
    private javax.swing.JTextField txtDescricaoCadPatri;
    private javax.swing.JTextField txtLocalCadPatri;
    private javax.swing.JTextField txtMarcaCadPatri;
    private javax.swing.JTextField txtModalAquiCadPatri;
    private javax.swing.JTextField txtModeloCadPatri;
    private javax.swing.JTextField txtNProcCadPatri;
    private javax.swing.JTextField txtNSerieCadPatri;
    private javax.swing.JTextField txtNfCadPatri;
    private javax.swing.JTextField txtNomeCadPatri;
    private javax.swing.JTextField txtValorCadPatri;
    // End of variables declaration//GEN-END:variables

}
