/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto-PC
 */
public class ConsultarUser extends javax.swing.JFrame {
    String action;
    /**
     * Creates new form Consultar
     */
    public ConsultarUser() {
        initComponents();
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }
    
    public ConsultarUser(String action) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.action = action;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLoginConsUser = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        txtNomeConsUser = new javax.swing.JTextField();
        btnBuscarConsUser = new javax.swing.JButton();
        btnLimparConsUser = new javax.swing.JButton();
        btnCancelarConsUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Login:");

        labelNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNome.setText("Nome:");

        btnBuscarConsUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarConsUser.setForeground(new java.awt.Color(0, 102, 255));
        btnBuscarConsUser.setText("Buscar");
        btnBuscarConsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConsUserActionPerformed(evt);
            }
        });

        btnLimparConsUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimparConsUser.setText("Limpar");
        btnLimparConsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparConsUserActionPerformed(evt);
            }
        });

        btnCancelarConsUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarConsUser.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelarConsUser.setText("Cancelar");
        btnCancelarConsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarConsUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnBuscarConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnLimparConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelarConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNome)
                            .addComponent(jLabel1)
                            .addComponent(txtLoginConsUser)
                            .addComponent(txtNomeConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarConsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarConsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConsUserActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarConsUserActionPerformed

    private void btnLimparConsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparConsUserActionPerformed
        txtLoginConsUser.setText("");
        txtNomeConsUser.setText("");
    }//GEN-LAST:event_btnLimparConsUserActionPerformed

    private void btnBuscarConsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConsUserActionPerformed
        if(UsuarioDAO.existsByUser(txtLoginConsUser.getText())){
            new CadastrarUser(UsuarioDAO.load(txtLoginConsUser.getText()),action).setVisible(true);
            this.dispose();
        }else{
            String login = UsuarioDAO.existsByName(txtNomeConsUser.getText());
            if(!login.equals("")){
                new CadastrarUser(UsuarioDAO.load(login),action).setVisible(true);
                this.dispose();
            }else{   
                JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
            }
        }
        
    }//GEN-LAST:event_btnBuscarConsUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarConsUser;
    private javax.swing.JButton btnCancelarConsUser;
    private javax.swing.JButton btnLimparConsUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JTextField txtLoginConsUser;
    private javax.swing.JTextField txtNomeConsUser;
    // End of variables declaration//GEN-END:variables
}
