/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import bean.Patrimonio;
import dao.PatrimonioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto-PC
 */
public class ConsultarPatri extends javax.swing.JFrame {

    Patrimonio patrimonio = new Patrimonio();
    /**
     * Creates new form Consultar
     */
    public ConsultarPatri() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    private boolean validateForm(){
        if (txtCodConsPatri.getText().equals("") &&
            txtNProcConsPatri.getText().equals("") &&
            txtNomeConsPatri.getText().equals("")){
            
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodConsPatri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNProcConsPatri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeConsPatri = new javax.swing.JTextField();
        btnBuscarConsPatri = new javax.swing.JButton();
        btnLimparConsPatri = new javax.swing.JButton();
        btnCancelarConsPatri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nº Processo Entrada");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        btnBuscarConsPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarConsPatri.setForeground(new java.awt.Color(0, 102, 255));
        btnBuscarConsPatri.setText("Buscar");
        btnBuscarConsPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConsPatriActionPerformed(evt);
            }
        });

        btnLimparConsPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimparConsPatri.setText("Limpar");
        btnLimparConsPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparConsPatriActionPerformed(evt);
            }
        });

        btnCancelarConsPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarConsPatri.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelarConsPatri.setText("Cancelar");
        btnCancelarConsPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarConsPatriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnLimparConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelarConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(txtCodConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNProcConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addComponent(txtNomeConsPatri)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNProcConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarConsPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparConsPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparConsPatriActionPerformed
        txtCodConsPatri.setText("");
        txtNProcConsPatri.setText("");
        txtNomeConsPatri.setText("");
    }//GEN-LAST:event_btnLimparConsPatriActionPerformed

    private void btnCancelarConsPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConsPatriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarConsPatriActionPerformed

    private void btnBuscarConsPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConsPatriActionPerformed
        if(!validateForm()){
            JOptionPane.showMessageDialog(null, "Preencha um dos campos!");
            return;
        }
        
        if(!txtCodConsPatri.getText().isEmpty()){
            patrimonio.setCodPatrimonio(Integer.parseInt(txtCodConsPatri.getText()));
        }
        
        if(!txtNProcConsPatri.getText().isEmpty()){
            patrimonio.setNumProcEntrada(Integer.parseInt(txtNProcConsPatri.getText()));
        }

        patrimonio.setNomePatrimonio(txtNomeConsPatri.getText());
        
        if(PatrimonioDAO.exists(patrimonio)){
            new CadastrarPatri(PatrimonioDAO.load(patrimonio)).setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Patrimônio não encontrado!");
        }
    }//GEN-LAST:event_btnBuscarConsPatriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarConsPatri;
    private javax.swing.JButton btnCancelarConsPatri;
    private javax.swing.JButton btnLimparConsPatri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCodConsPatri;
    private javax.swing.JTextField txtNProcConsPatri;
    private javax.swing.JTextField txtNomeConsPatri;
    // End of variables declaration//GEN-END:variables
}
