/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Neto-PC
 */
public class MeuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MeuPrincipal
     */
    public MeuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarMenu = new javax.swing.JButton();
        btnConsultarMenu = new javax.swing.JButton();
        btnSairMenu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCadastrarUsuario = new javax.swing.JMenuItem();
        btnConsultarUsuario = new javax.swing.JMenuItem();
        btnAlterarUsuario = new javax.swing.JMenuItem();
        btnExcluirUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnCadastrarPatri = new javax.swing.JMenuItem();
        btnConsultarPatri = new javax.swing.JMenuItem();
        btnAlterarPatri = new javax.swing.JMenuItem();
        btnExcluirPatri = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnPatriRelat = new javax.swing.JMenuItem();
        btnBaixaPatriRelat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                    Sistema Patrimônio");
        setSize(new java.awt.Dimension(615, 0));

        btnCadastrarMenu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCadastrarMenu.setText("Cadastrar");

        btnConsultarMenu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnConsultarMenu.setText("Consultar");

        btnSairMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSairMenu.setForeground(new java.awt.Color(255, 0, 0));
        btnSairMenu.setText("Sair");
        btnSairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairMenuActionPerformed(evt);
            }
        });

        jMenu1.setText("Usuário");

        btnCadastrarUsuario.setText("Cadastrar");
        jMenu1.add(btnCadastrarUsuario);

        btnConsultarUsuario.setText("Consultar");
        jMenu1.add(btnConsultarUsuario);

        btnAlterarUsuario.setText("Alterar");
        jMenu1.add(btnAlterarUsuario);

        btnExcluirUsuario.setText("Excluir");
        jMenu1.add(btnExcluirUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Patrimônio");

        btnCadastrarPatri.setText("Cadastrar");
        jMenu2.add(btnCadastrarPatri);

        btnConsultarPatri.setText("Consultar");
        jMenu2.add(btnConsultarPatri);

        btnAlterarPatri.setText("Alterar");
        jMenu2.add(btnAlterarPatri);

        btnExcluirPatri.setText("Excluir");
        jMenu2.add(btnExcluirPatri);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        btnPatriRelat.setText("Patrimônio");
        jMenu3.add(btnPatriRelat);

        btnBaixaPatriRelat.setText("Baixa Patrimonial");
        jMenu3.add(btnBaixaPatriRelat);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnCadastrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnConsultarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnSairMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAlterarPatri;
    private javax.swing.JMenuItem btnAlterarUsuario;
    private javax.swing.JMenuItem btnBaixaPatriRelat;
    private javax.swing.JButton btnCadastrarMenu;
    private javax.swing.JMenuItem btnCadastrarPatri;
    private javax.swing.JMenuItem btnCadastrarUsuario;
    private javax.swing.JButton btnConsultarMenu;
    private javax.swing.JMenuItem btnConsultarPatri;
    private javax.swing.JMenuItem btnConsultarUsuario;
    private javax.swing.JMenuItem btnExcluirPatri;
    private javax.swing.JMenuItem btnExcluirUsuario;
    private javax.swing.JMenuItem btnPatriRelat;
    private javax.swing.JButton btnSairMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
