/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import dao.PatrimonioDAO;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neto-PC
 */
public class RelatorioPatrimonio extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioPatrimonio
     */
    public RelatorioPatrimonio() {
        initComponents();
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        carregarTabela();
    }
    
    private void carregarTabela(){
        String[] tableColumnsName = {"Código", "Nº Proc.de Entrada", "Nº Nota Fiscal", 
            "Nome", "Marca", "Modelo", "Nº Série", "Descrição", "Mod. Aquisição", "Valor", "Local"}; 
        
        DefaultTableModel aModel = (DefaultTableModel) tabRelatPatri.getModel();
        aModel.setColumnIdentifiers(tableColumnsName); 

        tabRelatPatri.setModel(PatrimonioDAO.readAll(0, aModel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabRelatPatri = new javax.swing.JTable();
        btnSairRelatPatri = new javax.swing.JButton();
        btnImprimirRelatPatri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório Patrimônio");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("RELATÓRIO DE PATRIMÔNIO");

        tabRelatPatri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabRelatPatri.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        tabRelatPatri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nº Proc.de Entrada", "Nº Nota Fiscal", "Nome", "Marca", "Modelo", "Nº Série", "Descrição", "Mod. Aquisição", "Valor", "Local"
            }
        ));
        tabRelatPatri.setEnabled(false);
        jScrollPane1.setViewportView(tabRelatPatri);
        if (tabRelatPatri.getColumnModel().getColumnCount() > 0) {
            tabRelatPatri.getColumnModel().getColumn(0).setPreferredWidth(35);
            tabRelatPatri.getColumnModel().getColumn(1).setPreferredWidth(90);
            tabRelatPatri.getColumnModel().getColumn(2).setPreferredWidth(60);
            tabRelatPatri.getColumnModel().getColumn(3).setPreferredWidth(110);
            tabRelatPatri.getColumnModel().getColumn(4).setPreferredWidth(60);
            tabRelatPatri.getColumnModel().getColumn(5).setPreferredWidth(60);
            tabRelatPatri.getColumnModel().getColumn(6).setPreferredWidth(35);
            tabRelatPatri.getColumnModel().getColumn(7).setPreferredWidth(120);
            tabRelatPatri.getColumnModel().getColumn(8).setPreferredWidth(65);
            tabRelatPatri.getColumnModel().getColumn(9).setPreferredWidth(35);
            tabRelatPatri.getColumnModel().getColumn(10).setPreferredWidth(40);
        }

        btnSairRelatPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSairRelatPatri.setForeground(new java.awt.Color(255, 0, 0));
        btnSairRelatPatri.setText("Sair");
        btnSairRelatPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairRelatPatriActionPerformed(evt);
            }
        });

        btnImprimirRelatPatri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimirRelatPatri.setForeground(new java.awt.Color(0, 102, 255));
        btnImprimirRelatPatri.setText("Imprimir");
        btnImprimirRelatPatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatPatriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(329, 329, 329))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimirRelatPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSairRelatPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairRelatPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirRelatPatri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairRelatPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairRelatPatriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairRelatPatriActionPerformed

    private void btnImprimirRelatPatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatPatriActionPerformed
        try {
            tabRelatPatri.print(JTable.PrintMode.FIT_WIDTH,new MessageFormat("Relatório patrimonial"),null);
            JOptionPane.showMessageDialog(null, "Impressão realizada com sucesso!");
        } catch (PrinterException ex) {
            Logger.getLogger(RelatorioPatrimonio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirRelatPatriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirRelatPatri;
    private javax.swing.JButton btnSairRelatPatri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabRelatPatri;
    // End of variables declaration//GEN-END:variables
}
